from formula import hydraulicPowerOfThePump
from formula import temperatureAfterHeatExchange_OnHeatExchanger
from formula import temperatureAfterHeatExchange_OnBake
from formula import temperatureAfterHeatExchange_OnСolumn
from formula import volume_oil
from formula import desalination